from logging.config import fileConfig

from sqlalchemy import engine_from_config
from sqlalchemy import pool

from alembic import context
from sqlmodel import SQLModel
from app.core.database import engine
import app.models  # noqa: F401  # Ensure all tables are registered in SQLModel.metadata
import sqlmodel

# --- ensure bare `sqlmodel` is visible inside revision scripts ---------
import builtins as _builtins

# Some autogenerated migration files reference `sqlmodel.sql.sqltypes.*`
# without first importing the package.  Registering the module here
# makes the symbol resolvable via Python’s built‑in namespace lookup
# order (locals → globals → builtins) and avoids runtime errors.
_builtins.sqlmodel = sqlmodel  # type: ignore[attr-defined]

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Interpret the config file for Python logging.
# This line sets up loggers basically.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

#
# Use SQLModel's global metadata so that `alembic revision --autogenerate`
# can pick up all tables declared under app.models.*
target_metadata = SQLModel.metadata

# other values from the config, defined by the needs of env.py,
# can be acquired:
# my_important_option = config.get_main_option("my_important_option")
# ... etc.


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.

    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode."""
    connectable = engine

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
