"""add native core tables

Revision ID: 0811d79a9755
Revises: 8dea8d1e97bf
Create Date: 2025-07-31 22:56:14.848335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '0811d79a9755'
down_revision: Union[str, Sequence[str], None] = '8dea8d1e97bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sku_stats_run_id'), table_name='sku_stats')
    op.drop_index(op.f('ix_sku_stats_sku_id'), table_name='sku_stats')
    op.drop_table('sku_stats')
    op.drop_index(op.f('ix_receipts_receipt_date'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_sku_id'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_shipments_ship_date'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_sku_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_analysis_runs_run_datetime'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_skus_sku_code'), table_name='skus')
    op.drop_table('skus')
    op.drop_index(op.f('ix_analysisresult_run_datetime'), table_name='analysisresult')
    op.drop_table('analysisresult')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysisresult',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('run_datetime', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metrics', sqlite.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysisresult_run_datetime'), 'analysisresult', ['run_datetime'], unique=False)
    op.create_table('skus',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sku_code', sa.VARCHAR(length=64), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('volume_l', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skus_sku_code'), 'skus', ['sku_code'], unique=1)
    op.create_table('analysis_runs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('run_datetime', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('comment', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_run_datetime'), 'analysis_runs', ['run_datetime'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sku_id', sa.INTEGER(), nullable=False),
    sa.Column('ship_date', sa.DATE(), nullable=False),
    sa.Column('qty', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_sku_id'), 'shipments', ['sku_id'], unique=False)
    op.create_index(op.f('ix_shipments_ship_date'), 'shipments', ['ship_date'], unique=False)
    op.create_table('receipts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sku_id', sa.INTEGER(), nullable=False),
    sa.Column('receipt_date', sa.DATE(), nullable=False),
    sa.Column('qty', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipts_sku_id'), 'receipts', ['sku_id'], unique=False)
    op.create_index(op.f('ix_receipts_receipt_date'), 'receipts', ['receipt_date'], unique=False)
    op.create_table('sku_stats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('run_id', sa.INTEGER(), nullable=False),
    sa.Column('sku_id', sa.INTEGER(), nullable=False),
    sa.Column('inbound_30d', sa.INTEGER(), nullable=False),
    sa.Column('outbound_30d', sa.INTEGER(), nullable=False),
    sa.Column('turnover_ratio', sa.FLOAT(), nullable=True),
    sa.Column('percentile_rank', sa.FLOAT(), nullable=True),
    sa.Column('abc_class', sa.VARCHAR(length=1), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sku_stats_sku_id'), 'sku_stats', ['sku_id'], unique=False)
    op.create_index(op.f('ix_sku_stats_run_id'), 'sku_stats', ['run_id'], unique=False)
    # ### end Alembic commands ###
