"""fix analysis relationships

Revision ID: 487d69608b0d
Revises: 1feb460218b3
Create Date: 2025-07-30 03:41:15.477354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '487d69608b0d'
down_revision: Union[str, Sequence[str], None] = '1feb460218b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_runs_run_datetime'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_sku_stats_run_id'), table_name='sku_stats')
    op.drop_index(op.f('ix_sku_stats_sku_id'), table_name='sku_stats')
    op.drop_table('sku_stats')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sku_stats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('run_id', sa.INTEGER(), nullable=False),
    sa.Column('sku_id', sa.INTEGER(), nullable=False),
    sa.Column('inbound_30d', sa.INTEGER(), nullable=False),
    sa.Column('outbound_30d', sa.INTEGER(), nullable=False),
    sa.Column('turnover_ratio', sa.FLOAT(), nullable=True),
    sa.Column('percentile_rank', sa.FLOAT(), nullable=True),
    sa.Column('abc_class', sa.VARCHAR(length=1), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sku_stats_sku_id'), 'sku_stats', ['sku_id'], unique=False)
    op.create_index(op.f('ix_sku_stats_run_id'), 'sku_stats', ['run_id'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('run_datetime', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('comment', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_run_datetime'), 'analysis_runs', ['run_datetime'], unique=False)
    # ### end Alembic commands ###
