"""convert models to sqlmodel fields

Revision ID: b14dd101b363
Revises: 515dcbcd5cb9
Create Date: 2025-07-30 02:01:41.870589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'b14dd101b363'
down_revision: Union[str, Sequence[str], None] = '515dcbcd5cb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipments_date'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_sku_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_skus_sku_code'), table_name='skus')
    op.drop_table('skus')
    op.drop_index(op.f('ix_receipts_date'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_sku_id'), table_name='receipts')
    op.drop_table('receipts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipts',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('sku_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('qty', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipts_sku_id'), 'receipts', ['sku_id'], unique=False)
    op.create_index(op.f('ix_receipts_date'), 'receipts', ['date'], unique=False)
    op.create_table('skus',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sku_code', sa.VARCHAR(length=64), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('volume_l', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skus_sku_code'), 'skus', ['sku_code'], unique=1)
    op.create_table('analysis_results',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('run_datetime', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metrics', sqlite.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipments',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('sku_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('qty', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_sku_id'), 'shipments', ['sku_id'], unique=False)
    op.create_index(op.f('ix_shipments_date'), 'shipments', ['date'], unique=False)
    # ### end Alembic commands ###
