"""baseline_all_tables

Revision ID: 377130333335
Revises: 
Create Date: 2026-02-08 23:03:45.765790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '377130333335'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('location_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sku_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lot', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pack_qty', sa.Integer(), nullable=False),
    sa.Column('lot_date', sa.Date(), nullable=True),
    sa.Column('block_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('allocated_qty', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('column', sa.Integer(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('cases', sa.Float(), nullable=True),
    sa.Column('quality_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('location_id', 'sku_id', 'lot', 'pack_qty')
    )
    op.create_index(op.f('ix_inventory_column'), 'inventory', ['column'], unique=False)
    op.create_index(op.f('ix_inventory_depth'), 'inventory', ['depth'], unique=False)
    op.create_index(op.f('ix_inventory_level'), 'inventory', ['level'], unique=False)
    op.create_index(op.f('ix_inventory_location_id'), 'inventory', ['location_id'], unique=False)
    op.create_index(op.f('ix_inventory_lot'), 'inventory', ['lot'], unique=False)
    op.create_index(op.f('ix_inventory_sku_id'), 'inventory', ['sku_id'], unique=False)
    op.create_table('location_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_code', sa.String(length=8), nullable=False),
    sa.Column('quality_name', sa.String(length=16), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('column', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('numeric_id', sa.String(length=8), nullable=False),
    sa.Column('display_code', sa.String(length=64), nullable=True),
    sa.Column('can_receive', sa.Boolean(), nullable=False),
    sa.Column('highness', sa.Boolean(), nullable=False),
    sa.Column('bay_width_mm', sa.Integer(), nullable=False),
    sa.Column('bay_depth_mm', sa.Integer(), nullable=False),
    sa.Column('bay_height_mm', sa.Integer(), nullable=False),
    sa.Column('capacity_m3', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('disabled_from', sa.Date(), nullable=True),
    sa.Column('meta_json', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_code', 'quality_name', 'level', 'column', 'depth', name='uq_loc_master_zone')
    )
    op.create_index('ix_loc_master_zone', 'location_master', ['block_code', 'quality_name', 'can_receive', 'column'], unique=False)
    op.create_index(op.f('ix_location_master_block_code'), 'location_master', ['block_code'], unique=False)
    op.create_index(op.f('ix_location_master_id'), 'location_master', ['id'], unique=False)
    op.create_index(op.f('ix_location_master_numeric_id'), 'location_master', ['numeric_id'], unique=False)
    op.create_index(op.f('ix_location_master_quality_name'), 'location_master', ['quality_name'], unique=False)
    op.create_table('sku',
    sa.Column('sku_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pack_qty', sa.BigInteger(), nullable=True),
    sa.Column('length_mm', sa.Float(), nullable=True),
    sa.Column('width_mm', sa.Float(), nullable=True),
    sa.Column('height_mm', sa.Float(), nullable=True),
    sa.Column('volume_m3', sa.Numeric(precision=12, scale=8, asdecimal=False), nullable=True),
    sa.Column('oldness_days', sa.Float(), nullable=True),
    sa.Column('turnover_30d', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('sku_id')
    )
    op.create_table('skumetric',
    sa.Column('sku_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('oldness_days', sa.Integer(), nullable=True),
    sa.Column('turnover_days', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('sku_id')
    )
    op.create_table('recv_tx',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('trandate', sa.Date(), nullable=False),
    sa.Column('lot', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.sku_id'], name='fk_recvtx_sku'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ship_tx',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pack_qty', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('trandate', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.sku_id'], name='fk_shiptx_sku'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ship_tx')
    op.drop_table('recv_tx')
    op.drop_table('skumetric')
    op.drop_table('sku')
    op.drop_index(op.f('ix_location_master_quality_name'), table_name='location_master')
    op.drop_index(op.f('ix_location_master_numeric_id'), table_name='location_master')
    op.drop_index(op.f('ix_location_master_id'), table_name='location_master')
    op.drop_index(op.f('ix_location_master_block_code'), table_name='location_master')
    op.drop_index('ix_loc_master_zone', table_name='location_master')
    op.drop_table('location_master')
    op.drop_index(op.f('ix_inventory_sku_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_lot'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_location_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_level'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_depth'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_column'), table_name='inventory')
    op.drop_table('inventory')
    # ### end Alembic commands ###
