"""ship_tx fk to sku_id only

Revision ID: 425357a7886b
Revises: 
Create Date: 2025-08-07 18:57:35.467736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '425357a7886b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sku',
    sa.Column('sku_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pack_qty', sa.BigInteger(), nullable=True),
    sa.Column('length_mm', sa.Float(), nullable=True),
    sa.Column('width_mm', sa.Float(), nullable=True),
    sa.Column('height_mm', sa.Float(), nullable=True),
    sa.Column('volume_m3', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('oldness_days', sa.Float(), nullable=True),
    sa.Column('turnover_30d', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('sku_id')
    )
    op.create_table('inventory',
    sa.Column('location_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sku_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pack_qty', sa.Integer(), nullable=False),
    sa.Column('lot', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('block_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('column', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('lot_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.sku_id'], name='fk_inventory_sku'),
    sa.PrimaryKeyConstraint('location_id', 'sku_id', 'pack_qty', 'lot')
    )
    op.create_index(op.f('ix_inventory_sku_id'), 'inventory', ['sku_id'], unique=False)
    op.create_table('recv_tx',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('trandate', sa.Date(), nullable=False),
    sa.Column('lot', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.sku_id'], name='fk_recvtx_sku'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ship_tx',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pack_qty', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('trandate', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.sku_id'], name='fk_shiptx_sku'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ship_tx')
    op.drop_table('recv_tx')
    op.drop_index(op.f('ix_inventory_sku_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_table('sku')
    # ### end Alembic commands ###
